### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by pgularski** [pgularski/pysm#1]
![simple_on_off](https://cloud.githubusercontent.com/assets/3026621/15031178/bf5efb2a-124e-11e6-9748-0b5a5be60a30.png)
![complex](https://cloud.githubusercontent.com/assets/3026621/15031148/ad955f06-124e-11e6-865e-c7e3340f14cb.png)
![oven](https://cloud.githubusercontent.com/assets/3026621/15139952/b5e58cee-1690-11e6-9313-8ace79d5a74e.png)

**Comment by sivyyg** [comment]
Hi! I was wondering if these images generated from the state diagrams in the examples somehow? Or were they just hand-created in a tool? (I'm working a script that can generate flow diagrams from a state machine...)

**Comment by pgularski** [comment]
Hi, I used UMLet (www.umlet.com) to generate these. You can have a look at source files for the images here https://github.com/pgularski/pysm/tree/assets/assets  - all the *.uxf files.

**Comment by sivyyg** [comment]
thanks!
