### ISSUE TITLE
Doesn't work with micropython

### ISSUE THREAD

**Issue by vrubel** [pgularski/pysm#3]
It would be cool to get support for a micropython.

**Comment by pgularski** [comment]
This is actually a great idea. Will have a look at it.

**Comment by pgularski** [comment]
I started to tinker with pyboards only recently and for what it's worth I tweaked the pysm internals a bit to make it work with pyboards.

I tested it against the ESP-32S board and works flawlessly.

See the https://github.com/pgularski/upysm/ for details.

One can install it basically with
```python
import upip; pip.install('upysm')
```
Provided there's wifi support.

**Comment by mattytrentini** [comment]
Just wanted to say thanks! Recently I've been looking for a state machine module that I could use in MicroPython and had resigned myself to porting or creating a new library. `pysm` is exactly what I was looking for! Thanks again for going to the trouble to add MicroPython compatibility.

**Comment by pgularski** [comment]
Wow, for comments like this it's well worth sharing one's work as the open source software. Totally appreciate your feedback, Matt! Thanks!

**Comment by nevercast** [comment]
Hi, a commit has broken MicroPython compatibility, https://github.com/pgularski/pysm/commit/1fde9e14d85c3e2d35d61acc360133f5d5c48ea1#diff-5225765ccd6201cc9a3f939e749fb117R10

MicroPython does not have a `logging.StreamHandler` class. This has landed in `upysm`

**Comment by nevercast** [comment]
I worked around this by adding a stub class.
```
class StreamHandler:

    def __init__(self, stream=None):
        self.stream = stream
        self.terminator = '\n'

    def emit(self, record):
        pass

    def flush(self):
        pass

    def setStream(self, stream):
        old_stream = self.stream
        self.stream = stream
        return old_stream
```

and a stub method

```
class Logger:
    def addHandler(self, handler):
        pass
```

This is a Python 3.8 feature which MicroPython doesn't explictly support.

**Comment by pgularski** [comment]
Hi @nevercast ,
Thanks for having a look and letting me know. The logging WAS working last time I was testing the pysm library, so either you've got a different version of MicroPython or something has changed.

The workaround you sent is actually pretty much what I'd suggest. One more thing though, I'd wrap the import logging statement in the try/except block and would call your stub code only if the import of the logging module fails.

I'll take a look at it some time this week, hopefully. I don't have much time now tho and my ESP32 is somewhere around... I do have it, I swear :)

If you could craft a pull request, preferably with some tests, I'd appreciate it.

Once again, thanks for using the pysm module!

**Comment by nevercast** [comment]
I'm using the ESP32 port on MicroPython#master at github.com/micropython/micropython. The `logging` library, and `collections.[deque|defaultdict]` libraries came from github.com/micropython/micropython-lib. (I'm not using the native deque library at this time because you've used kwargs in your driver and the native library doesn't work with kwargs)

I'd say this port is probably the reference implementation, but I understand you may want to support ESP8266 also.
